name: cent
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  provider: ^6.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  intl: any

  localstore: ^1.4.0
  syncfusion_flutter_calendar: ^27.2.2
  device_preview: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/icons/



  generate: true

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Bold.ttf
          weight:700
      - asset: fonts/Poppins-Medium.ttf
          weight:500
      - asset: fonts/Poppins-Regular.ttf
          weight:400
      - asset: fonts/Poppins-SemiBold.ttf
          weight:600
  - family: Lato
    fonts:
      - asset: fonts/Lato-Black.ttf
      - asset: fonts/Lato-BlackItalic.ttf
      - asset: fonts/Lato-Bold.ttf
      - asset: fonts/Lato-BoldItalic.ttf
      - asset: fonts/Lato-Light.ttf
      - asset: fonts/Lato-LightItalic.ttf
      - asset: fonts/Lato-Regular.ttf
      - asset: fonts/Lato-Thin.ttf
      - asset: fonts/Lato-ThinItalic.ttf



